name: frontend-build
on:
    workflow_dispatch:
    push:
        branches:
            main
        paths:
            frontend/**

jobs: 
    upload:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-2

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: latest
                cache: npm

            - name: Setup folder for install
              run: mv ./frontend ../build
            
            - name: Install dependencies
              run: cd ../build && npm i

            - name: Build code
              run: cd ../build && npm run build
            
            - name: Sync S3 bucket 
              run: aws s3 sync ../build/dist/ s3://mapdeckglb.com --delete

            - name: Invalidate cloudfront
              run:  create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }}