name: frontend-build
on:
    workflow_dispatch:
    push:
        branches:
            main
        paths:
            frontend/**
            map-deck-viewer/**

jobs: 
    upload:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-2

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: latest
                cache: npm

            - name: Install dependencies
              run: npm i

            - name: Build map deck viewer
              run: npm run build -w @joshnice/map-deck-viewer

            - name: Build webdeckglb site
              run: npm run build -w @joshnice/webdeckglb-site
            
            - name: Sync S3 bucket 
              run: aws s3 sync ../frontend/dist/ s3://mapdeckglb.com --delete

            - name: Invalidate cloudfront
              run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths '/*'